
name: Terraform GCP Deployment

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write   # ✅ REQUIRED for Workload Identity

env:
  PROJECT_ID: terraform-gcp-498813
  REGION: us-central1

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # ✅ Authenticate to GCP using WIF
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/600365663293/locations/global/workloadIdentityPools/github-demo-pool/providers/github
          service_account: github-wif@terraform-gcp-498813.iam.gserviceaccount.com

      # ✅ Setup gcloud CLI
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      # ✅ Verify authentication (optional but useful)
      - name: Verify GCP Auth
        run: |
          gcloud auth list
          gcloud config list

      # ✅ Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # ✅ Terraform Init
      - name: Terraform Init
        run: terraform init
        

      # ✅ Terraform Validate
      - name: Terraform Validate
        run: terraform validate
        

      # ✅ Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        

      # ✅ Terraform Apply (only on main branch)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        